### ISSUE TITLE
Can't train a Roboflow dataset in Colab

### ISSUE THREAD

**Issue by jpardeck** [ultralytics/hub#201]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I get this in Colab every time I try.

Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: Authenticated ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/RJP4KUncmCou01qcoYu0 🚀
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████| 6.23M/6.23M [00:00<00:00, 72.8MB/s]
Ultralytics HUB: 0.000 GB dataset, 54.9/78.2 GB free disk space
Ultralytics YOLOv8.0.66 🚀 Python-3.9.16 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=https://app.roboflow.com/ds/jUk7mz6xfB?key=A9sVhxVtap, epochs=100, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train
Downloading https://app.roboflow.com/ds/jUk7mz6xfB?key=A9sVhxVtap to jUk7mz6xfB...
100%|██████████| 1.09G/1.09G [00:08<00:00, 143MB/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides)
    122             elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):
--> 123                 self.data = check_det_dataset(self.args.data)
    124                 if 'yaml_file' in self.data:

3 frames
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides)
    125                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    126         except Exception as e:
--> 127             raise RuntimeError(emojis(f"Dataset '{self.args.data}' error ❌ {e}")) from e
    128 
    129         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'https://app.roboflow.com/ds/jUk7mz6xfB?key=A9sVhxVtap' error ❌ unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

### Minimal Reproducible Example

1. Export dataset from Roboflow
2. Train for any verision of Yolo
3. When command is copied to Colab and run the above error is show

**Comment by jpardeck** [comment]
Realized I can't train with a custom dataset either, so there seems to be something wrong in general with Colab integration.

**Comment by glenn-jocher** [comment]
@jpardeck thank you for letting us know about this bug. We have reproduced and fixed this in https://github.com/ultralytics/ultralytics/pull/1871 which we just published to `ultralytics 8.0.67` now. Please update your ultraltyics package with `pip install -U ultralytics` and try to train again. 

Let us know if this resolves your issue, and feel free to tell us of any other ideas or problems you find!

**Comment by jpardeck** [comment]
That did not fix issue. From Colab after update:

Ultralytics YOLOv8.0.67 🚀 Python-3.9.16 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 24.4/78.2 GB disk)


Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: Authenticated ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/nzfbKPtyhmiFWr0m0JGD 🚀
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████| 6.23M/6.23M [00:00<00:00, 76.7MB/s]
Ultralytics HUB: 0.000 GB dataset, 54.9/78.2 GB free disk space
Ultralytics YOLOv8.0.67 🚀 Python-3.9.16 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=https://app.roboflow.com/ds/jUk7mz6xfB?key=A9sVhxVtap, epochs=100, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train
Downloading https://app.roboflow.com/ds/jUk7mz6xfB to jUk7mz6xfB...
100%|██████████| 1.09G/1.09G [00:07<00:00, 151MB/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py<https://localhost:8080/> in __init__(self, cfg, overrides, _callbacks)
    121             elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):
--> 122                 self.data = check_det_dataset(self.args.data)
    123                 if 'yaml_file' in self.data:

________________________________
3 frames
________________________________
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py<https://localhost:8080/> in __init__(self, cfg, overrides, _callbacks)
    124                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    125         except Exception as e:
--> 126             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    127
    128         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'https://app.roboflow.com/ds/jUk7mz6xfB' error ❌ unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

**Comment by jpardeck** [comment]
Also, if it helps. All of this worked until late yesterday (4/5). It broke yesterday afternoon.

**Comment by glenn-jocher** [comment]
@jpardeck got it. I think I'm able to reproduce. This appears to be a different issue than #199, so it's going to require a separate fix. I'll work on this and should have a new release published today with a fix.

**Comment by glenn-jocher** [comment]
@jpardeck I've fixed this in https://github.com/ultralytics/ultralytics/pull/1877 which we just published to ultralytics 8.0.68 now. Please update your ultraltyics package with `pip install -U ultralytics` and try to train again.

Let us know if this resolves your issue, and feel free to tell us of any other ideas or problems you find!

**Comment by jpardeck** [comment]
That corrected it. Thanks.

**Comment by UltralyticsAssistant** [comment]
That's great to hear, @jpardeck! I'm glad the issue is resolved now. If you have any more questions or run into any other issues, don't hesitate to reach out. Happy training! 🚀
