### ISSUE TITLE
Ultralytics Hub Android Permissions Error

### ISSUE THREAD

**Issue by ConorHackett98** [ultralytics/hub#261]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Hi,

I recently booted up Ultalytics Hub for the first time in a while but I was unable to use the detection mode as "Not all necessary permissions have been granted".  However, when I check in the System settings it shows that I have allowed camera permissions which is the only permission the app has requested.  In the past I think the app did request access to Files but it hasn't requested it this time.  I wonder if this might be where the problem is. 

I have tried Clearing cache and data, uninstalling then reinstalling and restarting my phone but nothing helped solve the issue.  

I was wondering if you might know a potential fix for this issue?

Kind Regards,
Conor.

(Image of application not running and of permissions granted to application)
![image](https://user-images.githubusercontent.com/56347543/236331974-ea6d9e87-2f96-47ff-b47c-222fb4933411.png)

### Environment

- YOLO: Ultralytics Hub
- Device: Samsung Galaxy S20 (FE 5G)
- OS: Android 13

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ConorHackett98 transferred issue here to HUB support repo. 

@sergiossm is our mobile developer in charge of the app but is unfortunately out of office through next week. Hopefully he can track down this issue when he returns.

**Comment by Miroslave11** [comment]
Hello,
I installed app today and I have exactly the same problem. 
1. I installed the app
2. I opened the app an I see  "Not all necessary permissions have been granted" But I checked that app has all permissions: for camera and access to files in the phone

my phone samsung S20 fe

**Comment by glenn-jocher** [comment]
@Miroslave11 hello,

Thank you for bringing this to our attention. We are aware of an issue where the HUB app may not function properly even after granting permissions for the camera and file storage. We apologize for the inconvenience this may have caused you.

Our mobile developer is currently out of office but we have noted this issue and will investigate when they return. In the meantime, we recommend checking the app's documentation or reaching out to its support team to confirm any additional permission requirements the app may need to function.

We appreciate your patience and understanding as we work towards resolving this problem.

**Comment by sergiossm** [comment]
@ConorHackett98 @Miroslave11 thank you for reporting the issue. It's now fixed in version 0.6.3, sorry for the inconvenience.

**Comment by ConorHackett98** [comment]
Hi sergiossm,

I've updated the app, deleted cache and data and uninstalled it, but the app still doesn't seem to request access to Storage.

When I boot the app it only asks for access to the camera which I allow, in previous versions it used to ask for acess to both the camera and storage.  I think this might be where the issue is coming from.

However, there is now an option on screen to allow permission for Storage (see below) but pressing the allow button doesn't do anything on my end.  

![image](https://user-images.githubusercontent.com/56347543/236859567-9005d071-e7f4-4ef0-9838-1dcb71ddacb1.png)

**Comment by sergiossm** [comment]
Hey @ConorHackett98, I'm sorry the fix is not working for you yet. It seems there's something wrong with the library we use for handling permissions. I'm out of office at the moment, but I'll try to find some time to look into it. Thank you for your patience.

**Comment by sergiossm** [comment]
@ConorHackett98 Issue resolved in version 0.6.4. Sorry for the delay, I'm out of the office and have struggled to find time to fix it.

**Comment by sergiossm** [comment]
@ConorHackett98 I'm glad to hear that 😄 Thank you for your patience
