### ISSUE TITLE
mAP zero while training

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#82]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

@glenn-jocher  the issue still prevails as i have tried training using a different dataset and even different model and tried both hub and custom colab notebook

**Comment by glenn-jocher** [comment]
@rexayyy this isn't a HUB issue, this is related to YOLOv5 and has been resolved in https://github.com/ultralytics/yolov5/pull/9037, so all you need to do is start from a fresh Colab notebook or update your local YOLOv5, i.e. `git pull` from inside your YOLOv5 directory.

**Comment by rexayyy** [comment]
I will try now and let you know right now

**Comment by rexayyy** [comment]
![Screen Shot 2022-08-21 at 4 04 55 AM](https://user-images.githubusercontent.com/97718899/185768886-27008f03-80ef-48bb-8523-b2ad653ffea1.png)
it is still the same

**Comment by glenn-jocher** [comment]
@rexayyy yes I'm able to reproduce. Am investigating now.

<img width="1124" alt="Screenshot 2022-08-21 at 02 06 16" src="https://user-images.githubusercontent.com/26833433/185769970-2f7e00a4-c726-40fc-bee9-7e324bc239c0.png">

**Comment by rexayyy** [comment]
I will do it again and let you know the progress

**Comment by rexayyy** [comment]
![image](https://user-images.githubusercontent.com/97718899/185771480-8f31aeab-1d9a-4c6c-bfb3-07611f089764.png)
I am still getting the issue

**Comment by MGIbrahim** [comment]
I am also having the same problem now
![Screenshot 2022-08-21 033303](https://user-images.githubusercontent.com/50985899/185771615-0117ee80-097d-4ad8-ac92-088ba750ae7c.png)

**Comment by glenn-jocher** [comment]
@rexayyy @MGIbrahim sorry about the persistent problems. I think I've resolved this now in https://github.com/ultralytics/yolov5/pull/9058

I created a new HUB model and trained in a **new Colab notebook** (YOLOv5n on COCO128 for 10 epochs) and everything looks fine now.

<img width="1309" alt="Screenshot 2022-08-21 at 03 39 30" src="https://user-images.githubusercontent.com/26833433/185771758-123ac5e8-e07c-4425-9d14-00b4b62bd14a.png">

**Comment by MGIbrahim** [comment]
@glenn-jocher Thanks for your quick response on this! I did a git pull and tried training again, but it still shows the mAP of 0. 
![Uploading Screenshot 2022-08-21 041514.png…]()

**Comment by rexayyy** [comment]
![Screen Shot 2022-08-21 at 7 21 38 AM](https://user-images.githubusercontent.com/97718899/185772570-00d100ee-5e05-4699-94db-c8c977e3e8e6.png)
Yes, it is still not fixed. I don`t know what has happened as it was working totally fine a few hours ago.

**Comment by glenn-jocher** [comment]
@MGIbrahim @rexayyy zero-mAP problem is being tracked down in https://github.com/ultralytics/yolov5/issues/9059

**Comment by robotwhispering** [comment]
@glenn-jocher do you notice that in the hub display in the above post, his Images and Labels coutns are messed up like mine are? But in the Hub image a few posts up, they're normal. And I haven't used Hub yet, only Colab and local. I wonder if there's some off-by-1 erroBut it shouldn't be wityh Hub, because I have yet to use it. I'm looking forward to trying it, but I haven't yet.
